"""empty message

Revision ID: 312559e450ec
Revises: 61bbc6683b2f
Create Date: 2020-01-14 22:03:35.211318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312559e450ec'
down_revision = '61bbc6683b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Donees_item_fkey', 'Donees', type_='foreignkey')
    op.drop_column('Donees', 'item')
    op.add_column('Items', sa.Column('donor_id', sa.Integer(), nullable=False))
    op.drop_constraint('Items_donor_fkey', 'Items', type_='foreignkey')
    op.create_foreign_key(None, 'Items', 'Donors', ['donor_id'], ['id'], ondelete='cascade')
    op.drop_column('Items', 'donor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Items', sa.Column('donor', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Items', type_='foreignkey')
    op.create_foreign_key('Items_donor_fkey', 'Items', 'Donors', ['donor'], ['user_name'])
    op.drop_column('Items', 'donor_id')
    op.add_column('Donees', sa.Column('item', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Donees_item_fkey', 'Donees', 'Items', ['item'], ['id'])
    # ### end Alembic commands ###
