"""empty message

Revision ID: 377a23dbc46b
Revises: bd4f3f27d9cf
Create Date: 2020-01-18 19:38:51.781810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377a23dbc46b'
down_revision = 'bd4f3f27d9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Items', 'city')
    op.drop_column('Items', 'state')
    op.drop_table('items')
    op.drop_table('donees')
    op.drop_table('donors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Items', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Items', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('catergory', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('condition', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('delivery', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('donor', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('donee', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['donee'], ['donees.id'], name='items_donee_fkey'),
    sa.ForeignKeyConstraint(['donor'], ['donors.id'], name='items_donor_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.create_table('donees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('organization', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='donees_pkey'),
    sa.UniqueConstraint('user_name', name='donees_user_name_key')
    )
    op.create_table('donors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='donors_pkey'),
    sa.UniqueConstraint('user_name', name='donors_user_name_key')
    )
    # ### end Alembic commands ###
