"""empty message

Revision ID: 4e2f3aa6c30b
Revises: d2042e744fb7
Create Date: 2020-01-14 21:42:19.228140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2f3aa6c30b'
down_revision = 'd2042e744fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Items', sa.Column('city', sa.String(), nullable=False))
    op.add_column('Items', sa.Column('state', sa.String(), nullable=False))
    op.drop_column('Items', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Items', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Items', 'state')
    op.drop_column('Items', 'city')
    # ### end Alembic commands ###
