"""empty message

Revision ID: 61bbc6683b2f
Revises: b3ded2b3f668
Create Date: 2020-01-14 21:57:46.808378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61bbc6683b2f'
down_revision = 'b3ded2b3f668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Donees_item_fkey', 'Donees', type_='foreignkey')
    op.drop_column('Donees', 'item')
    op.drop_constraint('Items_donor_fkey', 'Items', type_='foreignkey')
    op.create_foreign_key(None, 'Items', 'Donors', ['donor'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Items', type_='foreignkey')
    op.create_foreign_key('Items_donor_fkey', 'Items', 'Donors', ['donor'], ['user_name'])
    op.add_column('Donees', sa.Column('item', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Donees_item_fkey', 'Donees', 'Items', ['item'], ['id'])
    # ### end Alembic commands ###
