"""empty message

Revision ID: 79e98c31714a
Revises: 
Create Date: 2020-01-12 11:12:40.056942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e98c31714a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Items', sa.Column('donor', sa.String(), nullable=False))
    op.create_foreign_key(None, 'Items', 'Donors', ['donor'], ['user_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Items', type_='foreignkey')
    op.drop_column('Items', 'donor')
    # ### end Alembic commands ###
