"""empty message

Revision ID: 9c2a7a095a98
Revises: 377a23dbc46b
Create Date: 2020-01-22 16:54:58.409622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2a7a095a98'
down_revision = '377a23dbc46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Items', 'category',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('Items', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('Items', 'donee',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('nextval(\'"Items_donee_seq"\'::regclass)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Items', 'donee',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('nextval(\'"Items_donee_seq"\'::regclass)'))
    op.alter_column('Items', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('Items', 'category',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
