"""empty message

Revision ID: bd4f3f27d9cf
Revises: 6586e8f48b90
Create Date: 2020-01-18 14:13:56.730859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4f3f27d9cf'
down_revision = '6586e8f48b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Donees', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Donees', 'Items', ['item_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Donees', type_='foreignkey')
    op.drop_column('Donees', 'item_id')
    # ### end Alembic commands ###
