"""empty message

Revision ID: d2042e744fb7
Revises: 79e98c31714a
Create Date: 2020-01-12 11:30:59.832368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2042e744fb7'
down_revision = '79e98c31714a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Donees', sa.Column('item', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Donees', 'Items', ['item'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Donees', type_='foreignkey')
    op.drop_column('Donees', 'item')
    # ### end Alembic commands ###
